### ISSUE TITLE
76.21MB of dependencies

### ISSUE THREAD

**Issue by Nekonyx** [sindresorhus/get-urls#73]
![image](https://user-images.githubusercontent.com/16444061/125212095-e2ba5480-e2cc-11eb-957a-b0edec673919.png)

**Comment by sindresorhus** [comment]
That is not accurate. I'm seeing about 10 MB and most of that is caused by needing a safe regex engine as the one bundled in JS engines are too easily vulnerable.

<img width="964" alt="Screen Shot 2021-07-12 at 10 56 18" src="https://user-images.githubusercontent.com/170270/125259641-ca176200-e2ff-11eb-861c-cf82fe249eb7.png">

Closing as your issue not actionable.
